config/routes.rb
Rails.application.routes.draw do
  resources :states do
    collection do
      get 'search'
    end
  end

end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all
  end

  def search
    search_term = "%#{params[:search_term].downcase}%"
    @states = State.where("lower(abbreviation) like ? OR lower(name) like ?", search_term, search_term)
    render json: {states: @states}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autocomplete</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/states/index.html.erb
<h1>States</h1>
<%= form_tag search_states_path, method: :GET do %>
  <%= text_field_tag :search_term %>
<% end %>
<table id="result_table">
  <tr>
    <th>Abbreviation</th>
    <th>Name</th>
    <th>Capital City</th>
  </tr>
</table>

app/views/states/search.html.erb
<h1>Found States</h1>

<table>
  <tr>
    <th>Abbreviation</th>
    <th>Name</th>
    <th>Capital City</th>
  </tr>
  <% @states.each do |state| %>
    <tr>
      <td><%= state.abbreviation %></td>
      <td><%= state.name %></td>
      <td><%= state.capital %></td>
    </tr>
  <% end %>
</table>